[local]
localhost

[mongodb]
mongodb.viniashri.shop

[redis]
redis.viniashri.shop

[mysql]
mysql.viniashri.shop

[rabbitmq]
rabbitmq.viniashri.shop

[catalogue]
catalogue.viniashri.shop

[user]
user.viniashri.shop

[cart]
cart.viniashri.shop

[shipping]
shipping.viniashri.shop

[payment]
payment.viniashri.shop

[frontend]
frontend.viniashri.shop